use super::*;

pub const ANIMATION_EASINGS: &[&str] = &[
    "linear",
    "ease-in",
    "ease-out",
    "ease-in-out",
    "ease-in-quad",
    "ease-out-quad",
    "ease-in-out-quad",
    "ease-in-cubic",
    "ease-out-cubic",
    "ease-in-out-cubic",
    "ease-in-quart",
    "ease-out-quart",
    "ease-in-out-quart",
    "ease-in-quint",
    "ease-out-quint",
    "ease-in-out-quint",
    "ease-in-expo",
    "ease-out-expo",
    "ease-in-out-expo",
    "ease-in-circ",
    "ease-out-circ",
    "ease-in-out-circ",
    "ease-in-back",
    "ease-out-back",
    "ease-in-out-back",
    "ease-in-elastic",
    "ease-out-elastic",
    "ease-in-out-elastic",
    "ease-in-bounce",
    "ease-out-bounce",
    "ease-in-out-bounce",
];

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Span {
    pub line: usize,
    pub column: usize,
}

impl Span {
    pub fn line(line: usize) -> Self {
        Self { line, column: 1 }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Type {
    Bool,
    I64,
    F64,
    Str,
    Bytes,
    Image,
    ImageAllocation,
    ImageMemory,
    ImageError,
    DebugSpan,
    List(Box<Type>),
    Option(Box<Type>),
    Result(Box<Type>, Box<Type>),
    Combo(Box<Type>),
    Animation(Box<Type>),
    Markdown,
    Editor,
    Event,
    EventStatus,
    Key,
    PhysicalKey,
    KeyLocation,
    KeyPress,
    KeyRelease,
    KeyModifiers,
    Pixels,
    Padding,
    Degrees,
    Radians,
    Rotation,
    ContentFit,
    Color,
    Background,
    Gradient,
    LinearGradient,
    ColorStop,
    Font,
    FontFamily,
    FontWeight,
    FontStretch,
    FontStyle,
    ThemeMode,
    TextAlignment,
    TextShaping,
    TextWrapping,
    TextLineHeight,
    Length,
    Alignment,
    HorizontalAlignment,
    VerticalAlignment,
    Border,
    Radius,
    Shadow,
    Point,
    PointU32,
    Vector,
    Size,
    SizeU32,
    Rectangle,
    RectangleU32,
    Transformation,
    MouseInteraction,
    ScrollDelta,
    MouseButton,
    MouseCursor,
    MouseClick,
    TouchFinger,
    SystemInfo,
    Instant,
    WindowId,
    WindowScreenshot,
    WindowPosition,
    RedrawRequest,
    WindowDirection,
    WindowLevel,
    WindowMode,
    WindowAttention,
    WidgetId,
    WidgetTarget,
    TaskHandle,
    Named(String),
    Unit,
    Unknown,
}

impl Type {
    pub fn rust(&self, structs: &[ExternStruct]) -> String {
        match self {
            Self::Bool => "bool".into(),
            Self::I64 => "i64".into(),
            Self::F64 => "f64".into(),
            Self::Str => "::std::string::String".into(),
            Self::Bytes => "::std::vec::Vec<u8>".into(),
            Self::Image => "::iced::widget::image::Handle".into(),
            Self::ImageAllocation => "::iced::widget::image::Allocation".into(),
            Self::ImageMemory => "::std::sync::Weak<::iced::advanced::image::Memory>".into(),
            Self::ImageError => "::iced::widget::image::Error".into(),
            Self::DebugSpan => "::iced::debug::Span".into(),
            Self::List(inner) => format!("::std::vec::Vec<{}>", inner.rust(structs)),
            Self::Option(inner) => format!("::std::option::Option<{}>", inner.rust(structs)),
            Self::Result(output, error) => format!(
                "::std::result::Result<{}, {}>",
                output.rust(structs),
                error.rust(structs)
            ),
            Self::Combo(inner) => {
                format!("::iced::widget::combo_box::State<{}>", inner.rust(structs))
            }
            Self::Animation(inner) => match inner.as_ref() {
                Self::F64 => "::iced::Animation<f32>".into(),
                inner => format!("::iced::Animation<{}>", inner.rust(structs)),
            },
            Self::Markdown => "::iced::widget::markdown::Content".into(),
            Self::Editor => "::iced::widget::text_editor::Content".into(),
            Self::Event => "::iced::Event".into(),
            Self::EventStatus => "::iced::event::Status".into(),
            Self::Key => "::iced::keyboard::Key".into(),
            Self::PhysicalKey => "::iced::keyboard::key::Physical".into(),
            Self::KeyLocation => "::iced::keyboard::Location".into(),
            Self::KeyPress => "__IceKeyPress".into(),
            Self::KeyRelease => "__IceKeyRelease".into(),
            Self::KeyModifiers => "::iced::keyboard::Modifiers".into(),
            Self::Pixels => "::iced::Pixels".into(),
            Self::Padding => "::iced::Padding".into(),
            Self::Degrees => "::iced::Degrees".into(),
            Self::Radians => "::iced::Radians".into(),
            Self::Rotation => "::iced::Rotation".into(),
            Self::ContentFit => "::iced::ContentFit".into(),
            Self::Color => "::iced::Color".into(),
            Self::Background => "::iced::Background".into(),
            Self::Gradient => "::iced::Gradient".into(),
            Self::LinearGradient => "::iced::gradient::Linear".into(),
            Self::ColorStop => "::iced::gradient::ColorStop".into(),
            Self::Font => "::iced::Font".into(),
            Self::FontFamily => "::iced::font::Family".into(),
            Self::FontWeight => "::iced::font::Weight".into(),
            Self::FontStretch => "::iced::font::Stretch".into(),
            Self::FontStyle => "::iced::font::Style".into(),
            Self::ThemeMode => "::iced::theme::Mode".into(),
            Self::TextAlignment => "::iced::widget::text::Alignment".into(),
            Self::TextShaping => "::iced::widget::text::Shaping".into(),
            Self::TextWrapping => "::iced::widget::text::Wrapping".into(),
            Self::TextLineHeight => "::iced::widget::text::LineHeight".into(),
            Self::Length => "::iced::Length".into(),
            Self::Alignment => "::iced::Alignment".into(),
            Self::HorizontalAlignment => "::iced::alignment::Horizontal".into(),
            Self::VerticalAlignment => "::iced::alignment::Vertical".into(),
            Self::Border => "::iced::Border".into(),
            Self::Radius => "::iced::border::Radius".into(),
            Self::Shadow => "::iced::Shadow".into(),
            Self::Point => "::iced::Point".into(),
            Self::PointU32 => "::iced::Point<u32>".into(),
            Self::Vector => "::iced::Vector".into(),
            Self::Size => "::iced::Size".into(),
            Self::SizeU32 => "::iced::Size<u32>".into(),
            Self::Rectangle => "::iced::Rectangle".into(),
            Self::RectangleU32 => "::iced::Rectangle<u32>".into(),
            Self::Transformation => "::iced::Transformation".into(),
            Self::MouseInteraction => "::iced::mouse::Interaction".into(),
            Self::ScrollDelta => "::iced::mouse::ScrollDelta".into(),
            Self::MouseButton => "::iced::mouse::Button".into(),
            Self::MouseCursor => "::iced::mouse::Cursor".into(),
            Self::MouseClick => "::iced::advanced::mouse::Click".into(),
            Self::TouchFinger => "::iced::touch::Finger".into(),
            Self::SystemInfo => "__IceSystemInfo".into(),
            Self::Instant => "::iced::time::Instant".into(),
            Self::WindowId => "::iced::window::Id".into(),
            Self::WindowScreenshot => "::iced::window::Screenshot".into(),
            Self::WindowPosition => "::iced::window::Position".into(),
            Self::RedrawRequest => "::iced::window::RedrawRequest".into(),
            Self::WindowDirection => "::iced::window::Direction".into(),
            Self::WindowLevel => "::iced::window::Level".into(),
            Self::WindowMode => "::iced::window::Mode".into(),
            Self::WindowAttention => "::iced::window::UserAttention".into(),
            Self::WidgetId => "::iced::widget::Id".into(),
            Self::WidgetTarget => "__IceWidgetTarget".into(),
            Self::TaskHandle => "::iced::task::Handle".into(),
            Self::Named(name) => structs
                .iter()
                .find(|item| item.name == *name)
                .map_or_else(|| name.clone(), |item| item.rust_path.clone()),
            Self::Unit => "()".into(),
            Self::Unknown => "_".into(),
        }
    }

    pub fn display(&self) -> String {
        match self {
            Self::Bool => "bool".into(),
            Self::I64 => "i64".into(),
            Self::F64 => "f64".into(),
            Self::Str => "str".into(),
            Self::Bytes => "bytes".into(),
            Self::Image => "image".into(),
            Self::ImageAllocation => "image-allocation".into(),
            Self::ImageMemory => "image-memory".into(),
            Self::ImageError => "image-error".into(),
            Self::DebugSpan => "debug-span".into(),
            Self::List(inner) => format!("[{}]", inner.display()),
            Self::Option(inner) => format!("{}?", inner.display()),
            Self::Result(output, error) => {
                format!("result[{},{}]", output.display(), error.display())
            }
            Self::Combo(inner) => format!("combo[{}]", inner.display()),
            Self::Animation(inner) => format!("animation[{}]", inner.display()),
            Self::Markdown => "markdown".into(),
            Self::Editor => "editor".into(),
            Self::Event => "event".into(),
            Self::EventStatus => "event-status".into(),
            Self::Key => "key".into(),
            Self::PhysicalKey => "physical-key".into(),
            Self::KeyLocation => "key-location".into(),
            Self::KeyPress => "key-press".into(),
            Self::KeyRelease => "key-release".into(),
            Self::KeyModifiers => "key-modifiers".into(),
            Self::Pixels => "pixels".into(),
            Self::Padding => "padding".into(),
            Self::Degrees => "degrees".into(),
            Self::Radians => "radians".into(),
            Self::Rotation => "rotation".into(),
            Self::ContentFit => "content-fit".into(),
            Self::Color => "color".into(),
            Self::Background => "background".into(),
            Self::Gradient => "gradient".into(),
            Self::LinearGradient => "linear-gradient".into(),
            Self::ColorStop => "color-stop".into(),
            Self::Font => "font".into(),
            Self::FontFamily => "font-family".into(),
            Self::FontWeight => "font-weight".into(),
            Self::FontStretch => "font-stretch".into(),
            Self::FontStyle => "font-style".into(),
            Self::ThemeMode => "theme-mode".into(),
            Self::TextAlignment => "text-alignment".into(),
            Self::TextShaping => "text-shaping".into(),
            Self::TextWrapping => "text-wrapping".into(),
            Self::TextLineHeight => "text-line-height".into(),
            Self::Length => "length".into(),
            Self::Alignment => "alignment".into(),
            Self::HorizontalAlignment => "horizontal-alignment".into(),
            Self::VerticalAlignment => "vertical-alignment".into(),
            Self::Border => "border".into(),
            Self::Radius => "radius".into(),
            Self::Shadow => "shadow".into(),
            Self::Point => "point".into(),
            Self::PointU32 => "point-u32".into(),
            Self::Vector => "vector".into(),
            Self::Size => "size".into(),
            Self::SizeU32 => "size-u32".into(),
            Self::Rectangle => "rectangle".into(),
            Self::RectangleU32 => "rectangle-u32".into(),
            Self::Transformation => "transformation".into(),
            Self::MouseInteraction => "mouse-interaction".into(),
            Self::ScrollDelta => "scroll-delta".into(),
            Self::MouseButton => "mouse-button".into(),
            Self::MouseCursor => "mouse-cursor".into(),
            Self::MouseClick => "mouse-click".into(),
            Self::TouchFinger => "touch-finger".into(),
            Self::SystemInfo => "system-info".into(),
            Self::Instant => "instant".into(),
            Self::WindowId => "window-id".into(),
            Self::WindowScreenshot => "window-screenshot".into(),
            Self::WindowPosition => "window-position".into(),
            Self::RedrawRequest => "redraw-request".into(),
            Self::WindowDirection => "window-direction".into(),
            Self::WindowLevel => "window-level".into(),
            Self::WindowMode => "window-mode".into(),
            Self::WindowAttention => "window-attention".into(),
            Self::WidgetId => "widget-id".into(),
            Self::WidgetTarget => "widget-target".into(),
            Self::TaskHandle => "task-handle".into(),
            Self::Named(name) => name.clone(),
            Self::Unit => "unit".into(),
            Self::Unknown => "unknown".into(),
        }
    }
}
